/**
 * Stage build script: writes every stage in STAGE_DEFS as a
 * `score.mid` + `stage.json` pair under public/stages/<id>/, and
 * regenerates manifest.json so the loader picks them up.
 *
 * Run via `npm run gen:stages`.
 *
 * Roster: 10 Levels × 6 stages (5 graded + 1 exam) = 60 stages.
 * Each Level introduces ONE new rhythmic concept on top of the
 * previous one. Within a Level the five graded stages climb in
 * density / syncopation / subdivision; the `exam` stage previews an
 * element from the next Level so it feels like a bridge.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { buildScore } from './dsl/buildScore';
import {
  eighth,
  eighthDotted,
  eighthRest,
  eighthTriplet,
  fiveTuplet,
  h,
  hd,
  hr,
  q,
  qd,
  qr,
  quarterTriplet,
  septuplet,
  sixteenth,
  sixteenthDotted,
  sixteenthRest,
  sixteenthTriplet,
  sixTuplet,
  tempoChange,
  tie,
  tsChange,
  w,
} from './dsl/notes';
import { scoreToMidi } from './dsl/scoreToMidi';

interface StageDef {
  id: string;
  level: number;
  name: string;
  description: string;
  bpm: number;
  themeColor: string;
  indexInLevel?: number;
  isExam?: boolean;
  score: ReturnType<typeof buildScore>;
}

const OUT_DIR = 'public/stages';

// Per-level theme color — same palette as src/core/score/stages.ts so the
// authored stages and the offline fallback agree on Level coloring.
const COLOR = {
  1: '#9bd4a2',
  2: '#7cc8b3',
  3: '#5fbbc4',
  4: '#5ba8d9',
  5: '#7d8edf',
  6: '#a079d6',
  7: '#c46cbf',
  8: '#d96098',
  9: '#e2785a',
  10: '#E8612E',
} as const;

const STAGE_DEFS: readonly StageDef[] = [
  // ============================================================
  // Level 1 — quarter / half / whole notes (4/4)
  // ============================================================
  {
    id: 'level-1-1',
    level: 1,
    indexInLevel: 1,
    name: 'Level 1 — 1',
    description: '四分音符を歩く',
    bpm: 80,
    themeColor: COLOR[1],
    score: buildScore({ ts: [4, 4], bpm: 80 }, [
      q(), q(), q(), q(),
      q(), q(), q(), q(),
      h(), h(),
      w(),
      q(), q(), q(), q(),
      h(), h(),
      q(), q(), h(),
      w(),
    ]),
  },
  {
    id: 'level-1-2',
    level: 1,
    indexInLevel: 2,
    name: 'Level 1 — 2',
    description: '二分音符の伸びを感じる',
    bpm: 80,
    themeColor: COLOR[1],
    score: buildScore({ ts: [4, 4], bpm: 80 }, [
      h(), h(),
      q(), q(), h(),
      h(), q(), q(),
      w(),
      h(), h(),
      q(), q(), q(), q(),
      h(), h(),
      w(),
    ]),
  },
  {
    id: 'level-1-3',
    level: 1,
    indexInLevel: 3,
    name: 'Level 1 — 3',
    description: '全音符と二分音符の対話',
    bpm: 80,
    themeColor: COLOR[1],
    score: buildScore({ ts: [4, 4], bpm: 80 }, [
      w(),
      h(), h(),
      w(),
      q(), q(), h(),
      h(), q(), q(),
      w(),
      h(), q(), q(),
      w(),
    ]),
  },
  {
    id: 'level-1-4',
    level: 1,
    indexInLevel: 4,
    name: 'Level 1 — 4',
    description: '四分と二分のリレー',
    bpm: 80,
    themeColor: COLOR[1],
    score: buildScore({ ts: [4, 4], bpm: 80 }, [
      q(), q(), q(), q(),
      h(), q(), q(),
      q(), h(), q(),
      h(), h(),
      q(), q(), q(), q(),
      q(), h(), q(),
      h(), h(),
      w(),
    ]),
  },
  {
    id: 'level-1-5',
    level: 1,
    indexInLevel: 5,
    name: 'Level 1 — 5',
    description: '基本値の総まとめ',
    bpm: 80,
    themeColor: COLOR[1],
    score: buildScore({ ts: [4, 4], bpm: 80 }, [
      q(), q(), h(),
      h(), q(), q(),
      w(),
      q(), q(), q(), q(),
      h(), h(),
      q(), h(), q(),
      h(), q(), q(),
      w(),
    ]),
  },
  {
    id: 'level-1-exam',
    level: 1,
    indexInLevel: 6,
    isExam: true,
    name: 'Level 1 — Exam',
    description: '次レベルへ向け、休符を一足先に',
    bpm: 80,
    themeColor: COLOR[1],
    // Bridge to Level 2: sneak in a quarter rest.
    score: buildScore({ ts: [4, 4], bpm: 80 }, [
      q(), q(), q(), q(),
      h(), h(),
      q(), qr(), q(), q(),
      w(),
      q(), q(), h(),
      h(), q(), qr(),
      q(), q(), q(), q(),
      w(),
    ]),
  },

  // ============================================================
  // Level 2 — + quarter rest, 3/4 waltz
  // ============================================================
  {
    id: 'level-2-1',
    level: 2,
    indexInLevel: 1,
    name: 'Level 2 — 1',
    description: '四分休符の間合い',
    bpm: 90,
    themeColor: COLOR[2],
    score: buildScore({ ts: [4, 4], bpm: 90 }, [
      q(), qr(), q(), q(),
      h(), q(), qr(),
      q(), qr(), q(), q(),
      w(),
      q(), q(), qr(), q(),
      h(), q(), qr(),
      q(), qr(), q(), q(),
      w(),
    ]),
  },
  {
    id: 'level-2-2',
    level: 2,
    indexInLevel: 2,
    name: 'Level 2 — 2',
    description: '休符でひと呼吸',
    bpm: 90,
    themeColor: COLOR[2],
    score: buildScore({ ts: [4, 4], bpm: 90 }, [
      q(), q(), qr(), q(),
      qr(), q(), h(),
      q(), q(), q(), qr(),
      h(), h(),
      q(), qr(), h(),
      q(), q(), q(), qr(),
      h(), q(), qr(),
      w(),
    ]),
  },
  {
    id: 'level-2-3',
    level: 2,
    indexInLevel: 3,
    name: 'Level 2 — 3',
    description: '3/4 ワルツに入門',
    bpm: 90,
    themeColor: COLOR[2],
    score: buildScore({ ts: [3, 4], bpm: 90 }, [
      q(), q(), q(),
      h(), q(),
      q(), q(), q(),
      hd(),
      q(), q(), q(),
      q(), h(),
      h(), q(),
      hd(),
    ]),
  },
  {
    id: 'level-2-4',
    level: 2,
    indexInLevel: 4,
    name: 'Level 2 — 4',
    description: '3/4 + 四分休符',
    bpm: 90,
    themeColor: COLOR[2],
    score: buildScore({ ts: [3, 4], bpm: 90 }, [
      q(), qr(), q(),
      h(), q(),
      q(), q(), qr(),
      hd(),
      qr(), q(), q(),
      q(), h(),
      h(), qr(),
      hd(),
    ]),
  },
  {
    id: 'level-2-5',
    level: 2,
    indexInLevel: 5,
    name: 'Level 2 — 5',
    description: '4/4 と 3/4 を弾むように',
    bpm: 90,
    themeColor: COLOR[2],
    score: buildScore({ ts: [3, 4], bpm: 90 }, [
      q(), q(), q(),
      qr(), h(),
      h(), q(),
      q(), qr(), q(),
      hd(),
      q(), q(), q(),
      h(), qr(),
      hd(),
    ]),
  },
  {
    id: 'level-2-exam',
    level: 2,
    indexInLevel: 6,
    isExam: true,
    name: 'Level 2 — Exam',
    description: '次レベルへ向け、八分の予告',
    bpm: 90,
    themeColor: COLOR[2],
    // Bridge to Level 3: sneak in eighth notes.
    score: buildScore({ ts: [4, 4], bpm: 90 }, [
      q(), qr(), q(), q(),
      eighth(), eighth(), q(), h(),
      q(), q(), qr(), q(),
      w(),
      h(), eighth(), eighth(), q(),
      q(), qr(), eighth(), eighth(), q(),
      h(), q(), qr(),
      w(),
    ]),
  },

  // ============================================================
  // Level 3 — + eighth note / eighth rest
  // ============================================================
  {
    id: 'level-3-1',
    level: 3,
    indexInLevel: 1,
    name: 'Level 3 — 1',
    description: '八分音符を刻む',
    bpm: 95,
    themeColor: COLOR[3],
    score: buildScore({ ts: [4, 4], bpm: 95 }, [
      eighth(), eighth(), eighth(), eighth(), q(), q(),
      q(), eighth(), eighth(), h(),
      eighth(), eighth(), q(), eighth(), eighth(), q(),
      w(),
      eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), q(),
      h(), eighth(), eighth(), q(),
      q(), q(), eighth(), eighth(), q(),
      w(),
    ]),
  },
  {
    id: 'level-3-2',
    level: 3,
    indexInLevel: 2,
    name: 'Level 3 — 2',
    description: '八分休符の合いの手',
    bpm: 95,
    themeColor: COLOR[3],
    score: buildScore({ ts: [4, 4], bpm: 95 }, [
      eighth(), eighthRest(), eighth(), eighth(), q(), q(),
      q(), eighth(), eighthRest(), h(),
      q(), q(), eighth(), eighth(), q(),
      h(), h(),
      eighth(), eighthRest(), eighth(), eighth(), q(), q(),
      eighth(), eighth(), eighthRest(), eighth(), h(),
      q(), eighth(), eighthRest(), q(), q(),
      w(),
    ]),
  },
  {
    id: 'level-3-3',
    level: 3,
    indexInLevel: 3,
    name: 'Level 3 — 3',
    description: '裏拍を踏みしめる',
    bpm: 95,
    themeColor: COLOR[3],
    score: buildScore({ ts: [4, 4], bpm: 95 }, [
      eighthRest(), eighth(), eighth(), eighth(), q(), q(),
      q(), eighthRest(), eighth(), h(),
      eighthRest(), eighth(), q(), eighth(), eighth(), q(),
      w(),
      q(), eighthRest(), eighth(), eighthRest(), eighth(), q(),
      h(), eighth(), eighth(), eighth(), eighth(),
      eighthRest(), eighth(), eighthRest(), eighth(), h(),
      w(),
    ]),
  },
  {
    id: 'level-3-4',
    level: 3,
    indexInLevel: 4,
    name: 'Level 3 — 4',
    description: '3/4 拍子で八分音符',
    bpm: 95,
    themeColor: COLOR[3],
    score: buildScore({ ts: [3, 4], bpm: 95 }, [
      q(), eighth(), eighth(), q(),
      eighth(), eighth(), q(), q(),
      eighth(), eighth(), eighth(), eighth(), q(),
      hd(),
      q(), eighth(), eighthRest(), q(),
      eighth(), eighth(), eighth(), eighth(), q(),
      q(), q(), eighth(), eighth(),
      hd(),
    ]),
  },
  {
    id: 'level-3-5',
    level: 3,
    indexInLevel: 5,
    name: 'Level 3 — 5',
    description: '八分の連続と休符の織り交ぜ',
    bpm: 95,
    themeColor: COLOR[3],
    score: buildScore({ ts: [4, 4], bpm: 95 }, [
      eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(),
      q(), eighth(), eighthRest(), q(), q(),
      eighthRest(), eighth(), eighth(), eighth(), h(),
      eighth(), eighth(), q(), eighth(), eighth(), q(),
      q(), eighthRest(), eighth(), eighthRest(), eighth(), q(),
      eighth(), eighth(), eighth(), eighth(), q(), q(),
      h(), q(), qr(),
      w(),
    ]),
  },
  {
    id: 'level-3-exam',
    level: 3,
    indexInLevel: 6,
    isExam: true,
    name: 'Level 3 — Exam',
    description: '次レベルへ向け、付点四分の予告',
    bpm: 95,
    themeColor: COLOR[3],
    // Bridge to Level 4: introduce dotted quarter.
    score: buildScore({ ts: [4, 4], bpm: 95 }, [
      eighth(), eighth(), eighth(), eighth(), q(), q(),
      qd(), eighth(), h(),
      q(), eighthRest(), eighth(), eighth(), eighth(), q(),
      w(),
      qd(), eighth(), q(), q(),
      eighth(), eighth(), q(), qd(), eighth(),
      h(), eighth(), eighth(), q(),
      w(),
    ]),
  },

  // ============================================================
  // Level 4 — + dotted quarter / dotted eighth, 6/8 intro
  // ============================================================
  {
    id: 'level-4-1',
    level: 4,
    indexInLevel: 1,
    name: 'Level 4 — 1',
    description: '付点四分音符の躍動',
    bpm: 100,
    themeColor: COLOR[4],
    score: buildScore({ ts: [4, 4], bpm: 100 }, [
      qd(), eighth(), q(), q(),
      qd(), eighth(), h(),
      q(), qd(), eighth(), q(),
      w(),
      qd(), eighth(), qd(), eighth(),
      h(), qd(), eighth(),
      q(), q(), qd(), eighth(),
      w(),
    ]),
  },
  {
    id: 'level-4-2',
    level: 4,
    indexInLevel: 2,
    name: 'Level 4 — 2',
    description: '付点八分 + 十六分のスキップ',
    bpm: 100,
    themeColor: COLOR[4],
    score: buildScore({ ts: [4, 4], bpm: 100 }, [
      eighthDotted(), sixteenth(), q(), q(), q(),
      eighthDotted(), sixteenth(), eighthDotted(), sixteenth(), h(),
      q(), eighthDotted(), sixteenth(), h(),
      w(),
      eighthDotted(), sixteenth(), eighth(), eighth(), q(), q(),
      qd(), eighth(), eighthDotted(), sixteenth(), q(),
      eighth(), eighth(), eighthDotted(), sixteenth(), h(),
      w(),
    ]),
  },
  {
    id: 'level-4-3',
    level: 4,
    indexInLevel: 3,
    name: 'Level 4 — 3',
    description: '6/8 拍子に入門',
    bpm: 100,
    themeColor: COLOR[4],
    score: buildScore({ ts: [6, 8], bpm: 100 }, [
      qd(), qd(),
      q(), eighth(), qd(),
      eighth(), eighth(), eighth(), qd(),
      qd(), eighth(), eighth(), eighth(),
      qd(), q(), eighth(),
      eighth(), eighth(), eighth(), eighth(), eighth(), eighth(),
      q(), eighth(), q(), eighth(),
      qd(), qd(),
    ]),
  },
  {
    id: 'level-4-4',
    level: 4,
    indexInLevel: 4,
    name: 'Level 4 — 4',
    description: '6/8 + 付点四分の流れ',
    bpm: 100,
    themeColor: COLOR[4],
    score: buildScore({ ts: [6, 8], bpm: 100 }, [
      qd(), qd(),
      eighth(), eighth(), eighth(), qd(),
      q(), eighth(), q(), eighth(),
      qd(), eighth(), eighthRest(), eighth(),
      eighth(), eighth(), eighth(), eighth(), eighth(), eighth(),
      qd(), q(), eighth(),
      q(), eighth(), eighth(), eighth(), eighth(),
      qd(), qd(),
    ]),
  },
  {
    id: 'level-4-5',
    level: 4,
    indexInLevel: 5,
    name: 'Level 4 — 5',
    description: '4/4 と付点の総合演習',
    bpm: 100,
    themeColor: COLOR[4],
    score: buildScore({ ts: [4, 4], bpm: 100 }, [
      qd(), eighth(), eighthDotted(), sixteenth(), q(),
      q(), qd(), eighth(), q(),
      eighthDotted(), sixteenth(), eighth(), eighth(), h(),
      qd(), eighth(), h(),
      q(), q(), eighthDotted(), sixteenth(), q(),
      qd(), eighth(), eighthDotted(), sixteenth(), q(),
      h(), qd(), eighth(),
      w(),
    ]),
  },
  {
    id: 'level-4-exam',
    level: 4,
    indexInLevel: 6,
    isExam: true,
    name: 'Level 4 — Exam',
    description: '次レベルへ向け、十六分音符の予告',
    bpm: 100,
    themeColor: COLOR[4],
    // Bridge to Level 5: heavier sixteenth-note usage.
    score: buildScore({ ts: [4, 4], bpm: 100 }, [
      qd(), eighth(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), q(),
      eighthDotted(), sixteenth(), h(), q(),
      sixteenth(), sixteenth(), sixteenth(), sixteenth(), q(), h(),
      w(),
      q(), sixteenth(), sixteenth(), eighth(), q(), q(),
      eighth(), sixteenth(), sixteenth(), q(), h(),
      qd(), eighth(), h(),
      w(),
    ]),
  },

  // ============================================================
  // Level 5 — + sixteenths and sixteenth rest (4/4 + 6/8)
  // ============================================================
  {
    id: 'level-5-1',
    level: 5,
    indexInLevel: 1,
    name: 'Level 5 — 1',
    description: '十六分音符を均等に',
    bpm: 110,
    themeColor: COLOR[5],
    score: buildScore({ ts: [4, 4], bpm: 110 }, [
      sixteenth(), sixteenth(), sixteenth(), sixteenth(), q(), q(), q(),
      q(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), h(),
      sixteenth(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), h(),
      w(),
      q(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), q(), q(),
      eighth(), sixteenth(), sixteenth(), eighth(), sixteenth(), sixteenth(), h(),
      sixteenth(), sixteenth(), eighth(), q(), h(),
      w(),
    ]),
  },
  {
    id: 'level-5-2',
    level: 5,
    indexInLevel: 2,
    name: 'Level 5 — 2',
    description: '十六分休符でリズムを刻む',
    bpm: 110,
    themeColor: COLOR[5],
    score: buildScore({ ts: [4, 4], bpm: 110 }, [
      sixteenth(), sixteenthRest(), sixteenth(), sixteenth(), q(), h(),
      eighth(), sixteenth(), sixteenthRest(), q(), h(),
      sixteenthRest(), sixteenth(), sixteenth(), sixteenth(), q(), q(), q(),
      w(),
      sixteenth(), sixteenth(), sixteenthRest(), sixteenth(), q(), q(), q(),
      q(), sixteenthRest(), sixteenth(), eighth(), h(),
      eighthDotted(), sixteenth(), sixteenth(), sixteenthRest(), eighth(), q(),
      w(),
    ]),
  },
  {
    id: 'level-5-3',
    level: 5,
    indexInLevel: 3,
    name: 'Level 5 — 3',
    description: '6/8 で十六分を散りばめる',
    bpm: 110,
    themeColor: COLOR[5],
    score: buildScore({ ts: [6, 8], bpm: 110 }, [
      qd(), eighth(), sixteenth(), sixteenth(), eighth(),
      eighth(), sixteenth(), sixteenth(), eighth(), qd(),
      qd(), eighth(), eighth(), eighth(),
      sixteenth(), sixteenth(), eighth(), eighth(), qd(),
      eighth(), eighth(), sixteenth(), sixteenth(), qd(),
      qd(), eighth(), eighth(), sixteenth(), sixteenth(),
      sixteenth(), sixteenth(), eighth(), eighth(), q(), eighth(),
      qd(), qd(),
    ]),
  },
  {
    id: 'level-5-4',
    level: 5,
    indexInLevel: 4,
    name: 'Level 5 — 4',
    description: '裏裏のリズムを掴む',
    bpm: 110,
    themeColor: COLOR[5],
    score: buildScore({ ts: [4, 4], bpm: 110 }, [
      sixteenth(), sixteenthRest(), sixteenth(), sixteenthRest(), sixteenth(), sixteenthRest(), sixteenth(), sixteenthRest(), h(),
      eighthDotted(), sixteenth(), eighthDotted(), sixteenth(), h(),
      sixteenth(), sixteenth(), sixteenth(), sixteenth(), eighth(), eighth(), h(),
      w(),
      eighth(), sixteenth(), sixteenth(), eighth(), sixteenth(), sixteenth(), h(),
      q(), sixteenth(), sixteenthRest(), sixteenth(), sixteenth(), h(),
      sixteenthRest(), sixteenth(), eighth(), q(), h(),
      w(),
    ]),
  },
  {
    id: 'level-5-5',
    level: 5,
    indexInLevel: 5,
    name: 'Level 5 — 5',
    description: '十六分の総合演習',
    bpm: 110,
    themeColor: COLOR[5],
    score: buildScore({ ts: [4, 4], bpm: 110 }, [
      sixteenth(), sixteenth(), sixteenth(), sixteenth(), eighthDotted(), sixteenth(), q(), q(),
      eighth(), sixteenth(), sixteenth(), q(), eighth(), sixteenth(), sixteenth(), q(),
      sixteenthRest(), sixteenth(), eighth(), q(), eighthDotted(), sixteenth(), q(),
      q(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), q(), q(),
      h(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), q(),
      eighth(), eighth(), sixteenth(), sixteenth(), eighth(), q(), q(),
      sixteenth(), sixteenth(), sixteenth(), sixteenth(), q(), h(),
      w(),
    ]),
  },
  {
    id: 'level-5-exam',
    level: 5,
    indexInLevel: 6,
    isExam: true,
    name: 'Level 5 — Exam',
    description: '次レベルへ向け、シンコペーションの予告',
    bpm: 110,
    themeColor: COLOR[5],
    // Bridge to Level 6: early syncopation (eighth-quarter-eighth).
    score: buildScore({ ts: [4, 4], bpm: 110 }, [
      eighth(), q(), q(), q(), eighth(),
      sixteenth(), sixteenth(), eighth(), q(), eighth(), q(), eighth(),
      q(), eighth(), q(), eighth(), q(),
      w(),
      eighth(), qd(), q(), q(),
      eighth(), q(), eighth(), eighth(), q(), eighth(),
      sixteenth(), sixteenth(), eighth(), q(), h(),
      w(),
    ]),
  },

  // ============================================================
  // Level 6 — + syncopation, ties across barlines
  // ============================================================
  {
    id: 'level-6-1',
    level: 6,
    indexInLevel: 1,
    name: 'Level 6 — 1',
    description: 'シンコペーション入門',
    bpm: 120,
    themeColor: COLOR[6],
    score: buildScore({ ts: [4, 4], bpm: 120 }, [
      eighth(), q(), q(), q(), eighth(),
      q(), eighth(), q(), eighth(), q(),
      eighth(), q(), eighth(), eighth(), q(), eighth(),
      w(),
      eighth(), q(), eighth(), eighth(), q(), eighth(),
      q(), eighth(), q(), eighth(), q(),
      h(), eighth(), q(), eighth(),
      w(),
    ]),
  },
  {
    id: 'level-6-2',
    level: 6,
    indexInLevel: 2,
    name: 'Level 6 — 2',
    description: '小節を跨ぐタイ',
    bpm: 120,
    themeColor: COLOR[6],
    score: buildScore({ ts: [4, 4], bpm: 120 }, [
      // measure 1-2: dotted half tied across to a quarter
      h(), tie(q(), w()), h(),
      q(), q(), h(),
      w(),
      // measure 5-6: half tied to half (sustained whole across the bar)
      h(), tie(h(), h()), h(),
      eighth(), eighth(), q(), h(),
      tie(q(), h()), q(), q(),
      w(),
    ]),
  },
  {
    id: 'level-6-3',
    level: 6,
    indexInLevel: 3,
    name: 'Level 6 — 3',
    description: 'シンコペとタイの混合',
    bpm: 120,
    themeColor: COLOR[6],
    score: buildScore({ ts: [4, 4], bpm: 120 }, [
      eighth(), q(), q(), q(), eighth(),
      tie(eighth(), q()), eighth(), eighth(), q(), eighth(),
      q(), eighth(), eighth(), h(),
      w(),
      eighth(), q(), eighth(), eighth(), eighth(), q(),
      tie(q(), eighth()), eighth(), h(),
      q(), eighth(), eighth(), q(), q(),
      w(),
    ]),
  },
  {
    id: 'level-6-4',
    level: 6,
    indexInLevel: 4,
    name: 'Level 6 — 4',
    description: 'アンチシペーションで先取り',
    bpm: 120,
    themeColor: COLOR[6],
    score: buildScore({ ts: [4, 4], bpm: 120 }, [
      eighth(), q(), eighth(), eighth(), q(), eighth(),
      tie(eighth(), h()), eighth(), q(),
      q(), eighth(), q(), eighth(), q(),
      w(),
      eighth(), q(), q(), q(), eighth(),
      tie(eighth(), q()), tie(eighth(), q()), q(),
      eighth(), q(), eighth(), h(),
      w(),
    ]),
  },
  {
    id: 'level-6-5',
    level: 6,
    indexInLevel: 5,
    name: 'Level 6 — 5',
    description: '裏拍とタイで踊る',
    bpm: 120,
    themeColor: COLOR[6],
    score: buildScore({ ts: [4, 4], bpm: 120 }, [
      sixteenth(), sixteenth(), eighth(), q(), eighth(), q(), eighth(),
      tie(eighth(), q()), eighth(), eighth(), q(), eighth(),
      q(), tie(eighth(), q()), eighth(), q(),
      w(),
      eighth(), q(), eighth(), eighth(), eighth(), eighth(), eighth(),
      tie(q(), h()), q(), q(),
      eighth(), q(), eighth(), q(), q(),
      w(),
    ]),
  },
  {
    id: 'level-6-exam',
    level: 6,
    indexInLevel: 6,
    isExam: true,
    name: 'Level 6 — Exam',
    description: '次レベルへ向け、三連符の予告',
    bpm: 120,
    themeColor: COLOR[6],
    // Bridge to Level 7: introduce triplets.
    score: buildScore({ ts: [4, 4], bpm: 120 }, [
      eighthTriplet(), eighthTriplet(), eighthTriplet(), q(), h(),
      eighth(), q(), q(), q(), eighth(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(),
      w(),
      tie(q(), eighth()), eighth(), q(), q(),
      q(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(),
      eighth(), q(), eighth(), h(),
      w(),
    ]),
  },

  // ============================================================
  // Level 7 — + triplets, sextuplets, 9/8
  // ============================================================
  {
    id: 'level-7-1',
    level: 7,
    indexInLevel: 1,
    name: 'Level 7 — 1',
    description: '三連符を流暢に',
    bpm: 130,
    themeColor: COLOR[7],
    score: buildScore({ ts: [4, 4], bpm: 130 }, [
      eighthTriplet(), eighthTriplet(), eighthTriplet(), q(), h(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(),
      q(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(),
      w(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), q(), q(),
      h(), eighthTriplet(), eighthTriplet(), eighthTriplet(), q(),
      quarterTriplet(), quarterTriplet(), quarterTriplet(), h(),
      w(),
    ]),
  },
  {
    id: 'level-7-2',
    level: 7,
    indexInLevel: 2,
    name: 'Level 7 — 2',
    description: '4 連 vs 3 連の対比',
    bpm: 130,
    themeColor: COLOR[7],
    score: buildScore({ ts: [4, 4], bpm: 130 }, [
      sixteenth(), sixteenth(), sixteenth(), sixteenth(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), h(),
      q(), eighthTriplet(), eighthTriplet(), eighthTriplet(), q(), q(),
      w(),
      sixteenth(), sixteenth(), sixteenth(), sixteenth(), eighthTriplet(), eighthTriplet(), eighthTriplet(), q(), q(),
      quarterTriplet(), quarterTriplet(), quarterTriplet(), h(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(),
      w(),
    ]),
  },
  {
    id: 'level-7-3',
    level: 7,
    indexInLevel: 3,
    name: 'Level 7 — 3',
    description: '六連符の旋回',
    bpm: 130,
    themeColor: COLOR[7],
    score: buildScore({ ts: [4, 4], bpm: 130 }, [
      sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), q(), h(),
      q(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), h(),
      sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), q(), h(),
      w(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), h(),
      q(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(),
      sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), q(), h(),
      w(),
    ]),
  },
  {
    id: 'level-7-4',
    level: 7,
    indexInLevel: 4,
    name: 'Level 7 — 4',
    description: '9/8 拍子に親しむ',
    bpm: 130,
    themeColor: COLOR[7],
    score: buildScore({ ts: [9, 8], bpm: 130 }, [
      qd(), qd(), qd(),
      eighth(), eighth(), eighth(), qd(), qd(),
      qd(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(),
      qd(), qd(), q(), eighth(),
      eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(),
      qd(), q(), eighth(), qd(),
      q(), eighth(), qd(), eighth(), eighth(), eighth(),
      qd(), qd(), qd(),
    ]),
  },
  {
    id: 'level-7-5',
    level: 7,
    indexInLevel: 5,
    name: 'Level 7 — 5',
    description: '三連 + タイの華麗な技巧',
    bpm: 130,
    themeColor: COLOR[7],
    score: buildScore({ ts: [4, 4], bpm: 130 }, [
      eighthTriplet(), eighthTriplet(), eighthTriplet(), q(), q(), q(),
      tie(eighthTriplet(), quarterTriplet()), eighthTriplet(), eighthTriplet(), h(),
      quarterTriplet(), quarterTriplet(), quarterTriplet(), h(),
      w(),
      eighth(), q(), eighth(), eighthTriplet(), eighthTriplet(), eighthTriplet(), q(),
      sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), q(), q(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(),
      w(),
    ]),
  },
  {
    id: 'level-7-exam',
    level: 7,
    indexInLevel: 6,
    isExam: true,
    name: 'Level 7 — Exam',
    description: '次レベルへ向け、五連符の予告',
    bpm: 130,
    themeColor: COLOR[7],
    // Bridge to Level 8: introduce quintuplets.
    score: buildScore({ ts: [4, 4], bpm: 130 }, [
      fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), q(), h(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), q(), h(),
      fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(),
      w(),
      q(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), h(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(),
      h(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), q(),
      w(),
    ]),
  },

  // ============================================================
  // Level 8 — + quintuplets, septuplets, 5/8, 7/8
  // ============================================================
  {
    id: 'level-8-1',
    level: 8,
    indexInLevel: 1,
    name: 'Level 8 — 1',
    description: '五連符を四拍の中に',
    bpm: 140,
    themeColor: COLOR[8],
    score: buildScore({ ts: [4, 4], bpm: 140 }, [
      fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), q(), h(),
      q(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), h(),
      fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), h(),
      w(),
      eighth(), eighth(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), h(),
      q(), q(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(),
      h(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), q(),
      w(),
    ]),
  },
  {
    id: 'level-8-2',
    level: 8,
    indexInLevel: 2,
    name: 'Level 8 — 2',
    description: '七連符の挑戦',
    bpm: 140,
    themeColor: COLOR[8],
    score: buildScore({ ts: [4, 4], bpm: 140 }, [
      ...septuplet(), q(), h(),
      q(), ...septuplet(), h(),
      ...septuplet(), ...septuplet(), h(),
      w(),
      eighth(), eighth(), ...septuplet(), h(),
      h(), ...septuplet(), q(),
      ...septuplet(), q(), h(),
      w(),
    ]),
  },
  {
    id: 'level-8-3',
    level: 8,
    indexInLevel: 3,
    name: 'Level 8 — 3',
    description: '5/8 拍子に飛び込む',
    bpm: 140,
    themeColor: COLOR[8],
    score: buildScore({ ts: [5, 8], bpm: 140 }, [
      q(), qd(),
      eighth(), eighth(), eighth(), q(),
      qd(), eighth(), eighth(),
      eighth(), eighth(), eighth(), eighth(), eighth(),
      q(), q(), eighth(),
      eighth(), eighth(), eighth(), qd(),
      qd(), q(),
      eighth(), eighth(), eighth(), eighth(), eighth(),
    ]),
  },
  {
    id: 'level-8-4',
    level: 8,
    indexInLevel: 4,
    name: 'Level 8 — 4',
    description: '7/8 のうねり',
    bpm: 140,
    themeColor: COLOR[8],
    score: buildScore({ ts: [7, 8], bpm: 140 }, [
      qd(), q(), q(),
      q(), q(), qd(),
      eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(),
      qd(), eighth(), eighth(), q(),
      q(), eighth(), eighth(), eighth(), eighth(), eighth(),
      qd(), q(), q(),
      eighth(), eighth(), qd(), q(),
      qd(), qd(), eighth(),
    ]),
  },
  {
    id: 'level-8-5',
    level: 8,
    indexInLevel: 5,
    name: 'Level 8 — 5',
    description: '異拍子の総合演習',
    bpm: 140,
    themeColor: COLOR[8],
    score: buildScore({ ts: [4, 4], bpm: 140 }, [
      fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), ...septuplet(), h(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), h(),
      ...septuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), h(),
      w(),
      q(), ...septuplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), q(),
      fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), q(), h(),
      quarterTriplet(), quarterTriplet(), quarterTriplet(), h(),
      w(),
    ]),
  },
  {
    id: 'level-8-exam',
    level: 8,
    indexInLevel: 6,
    isExam: true,
    name: 'Level 8 — Exam',
    description: '次レベルへ向け、5/4 拍子の予告',
    bpm: 140,
    themeColor: COLOR[8],
    // Bridge to Level 9: 5/4 irregular meter.
    score: buildScore({ ts: [5, 4], bpm: 140 }, [
      q(), q(), q(), q(), q(),
      h(), q(), h(),
      eighth(), eighth(), q(), eighth(), eighth(), q(), q(),
      q(), eighthTriplet(), eighthTriplet(), eighthTriplet(), h(), q(),
      h(), q(), q(), q(),
      fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), q(), q(), q(), q(),
      q(), q(), q(), h(),
      w(), q(),
    ]),
  },

  // ============================================================
  // Level 9 — + irregular meter (5/4, 7/8), hemiola, compound regroup
  // ============================================================
  {
    id: 'level-9-1',
    level: 9,
    indexInLevel: 1,
    name: 'Level 9 — 1',
    description: '5/4 拍子で歩を進める',
    bpm: 152,
    themeColor: COLOR[9],
    score: buildScore({ ts: [5, 4], bpm: 152 }, [
      q(), q(), q(), q(), q(),
      h(), q(), q(), q(),
      q(), h(), eighth(), eighth(), eighth(), eighth(),
      hd(), h(),
      eighth(), eighth(), q(), q(), q(), q(),
      q(), q(), h(), q(),
      h(), eighth(), eighth(), q(), q(),
      w(), q(),
    ]),
  },
  {
    id: 'level-9-2',
    level: 9,
    indexInLevel: 2,
    name: 'Level 9 — 2',
    description: '7/8 拍子の躍動',
    bpm: 152,
    themeColor: COLOR[9],
    score: buildScore({ ts: [7, 8], bpm: 152 }, [
      qd(), q(), q(),
      q(), qd(), q(),
      q(), q(), qd(),
      eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(),
      qd(), eighth(), eighth(), eighth(), eighth(),
      eighth(), eighth(), qd(), eighth(), eighth(),
      eighth(), eighth(), eighth(), eighth(), qd(),
      qd(), q(), q(),
    ]),
  },
  {
    id: 'level-9-3',
    level: 9,
    indexInLevel: 3,
    name: 'Level 9 — 3',
    description: 'ヘミオラ — 3 を 2 に組替',
    bpm: 152,
    themeColor: COLOR[9],
    // 6/4 measures grouped as 3+3 vs 2+2+2 to evoke a hemiola feel.
    score: buildScore({ ts: [6, 4], bpm: 152 }, [
      qd(), qd(), qd(), qd(),
      q(), q(), q(), q(), q(), q(),
      qd(), qd(), q(), q(), q(),
      h(), h(), h(),
      qd(), q(), eighth(), qd(), q(), eighth(),
      q(), q(), q(), qd(), qd(),
      h(), q(), h(), q(),
      hd(), hd(),
    ]),
  },
  {
    id: 'level-9-4',
    level: 9,
    indexInLevel: 4,
    name: 'Level 9 — 4',
    description: '複合拍子の組替え (9/8 ⇄ 6/8)',
    bpm: 152,
    themeColor: COLOR[9],
    score: buildScore({ ts: [9, 8], bpm: 152 }, [
      qd(), qd(), qd(),
      eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(),
      tsChange(6, 8),
      qd(), qd(),
      eighth(), eighth(), eighth(), qd(),
      tsChange(9, 8),
      qd(), q(), eighth(), qd(),
      eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(), eighth(),
      tsChange(6, 8),
      qd(), eighth(), eighth(), eighth(),
      qd(), qd(),
    ]),
  },
  {
    id: 'level-9-5',
    level: 9,
    indexInLevel: 5,
    name: 'Level 9 — 5',
    description: '変則拍子の総合演習',
    bpm: 152,
    themeColor: COLOR[9],
    score: buildScore({ ts: [5, 4], bpm: 152 }, [
      q(), q(), q(), h(),
      h(), q(), eighth(), eighth(), q(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), q(), q(), q(),
      tsChange(7, 8),
      qd(), q(), q(),
      eighth(), eighth(), eighth(), qd(), q(),
      tsChange(5, 4),
      h(), q(), h(),
      q(), q(), eighth(), eighth(), q(), q(),
      w(), q(),
    ]),
  },
  {
    id: 'level-9-exam',
    level: 9,
    indexInLevel: 6,
    isExam: true,
    name: 'Level 9 — Exam',
    description: '次レベルへ向け、拍子切替の予告',
    bpm: 152,
    themeColor: COLOR[9],
    // Bridge to Level 10: meter changes mid-piece + tempo bump.
    score: buildScore({ ts: [4, 4], bpm: 152 }, [
      q(), q(), eighth(), eighth(), q(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), h(), q(),
      tsChange(5, 8),
      qd(), q(),
      eighth(), eighth(), eighth(), eighth(), eighth(),
      tsChange(7, 8),
      qd(), q(), q(),
      eighth(), eighth(), eighth(), eighth(), qd(),
      tsChange(4, 4),
      tempoChange(168),
      q(), q(), q(), q(),
      w(),
    ]),
  },

  // ============================================================
  // Level 10 — mixed meter / meter-change / cross-rhythm / tempo change
  // ============================================================
  {
    id: 'level-10-1',
    level: 10,
    indexInLevel: 1,
    name: 'Level 10 — 1',
    description: '拍子切替に慣れる',
    bpm: 168,
    themeColor: COLOR[10],
    score: buildScore({ ts: [4, 4], bpm: 168 }, [
      q(), q(), q(), q(),
      h(), eighth(), eighth(), eighth(), eighth(),
      tsChange(3, 4),
      q(), q(), q(),
      h(), q(),
      tsChange(4, 4),
      q(), eighth(), eighth(), q(), q(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), h(), q(),
      tsChange(6, 8),
      qd(), qd(),
      eighth(), eighth(), eighth(), qd(),
    ]),
  },
  {
    id: 'level-10-2',
    level: 10,
    indexInLevel: 2,
    name: 'Level 10 — 2',
    description: 'テンポチェンジを乗りこなす',
    bpm: 168,
    themeColor: COLOR[10],
    score: buildScore({ ts: [4, 4], bpm: 168 }, [
      q(), q(), q(), q(),
      h(), q(), q(),
      tempoChange(120),
      eighth(), eighth(), q(), h(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), q(), h(),
      tempoChange(168),
      q(), eighth(), eighth(), q(), q(),
      sixteenth(), sixteenth(), sixteenth(), sixteenth(), q(), h(),
      tempoChange(96),
      hd(), q(),
      w(),
    ]),
  },
  {
    id: 'level-10-3',
    level: 10,
    indexInLevel: 3,
    name: 'Level 10 — 3',
    description: 'クロスリズム 3 against 2',
    bpm: 168,
    themeColor: COLOR[10],
    score: buildScore({ ts: [4, 4], bpm: 168 }, [
      quarterTriplet(), quarterTriplet(), quarterTriplet(), h(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), eighth(), eighth(), h(),
      quarterTriplet(), quarterTriplet(), quarterTriplet(), q(), q(),
      eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), sixteenth(), sixteenth(), sixteenth(), sixteenth(), q(),
      h(), quarterTriplet(), quarterTriplet(), quarterTriplet(),
      sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), q(), h(),
      quarterTriplet(), quarterTriplet(), quarterTriplet(), eighth(), eighth(), q(),
      w(),
    ]),
  },
  {
    id: 'level-10-4',
    level: 10,
    indexInLevel: 4,
    name: 'Level 10 — 4',
    description: '混合拍子の連結',
    bpm: 168,
    themeColor: COLOR[10],
    score: buildScore({ ts: [5, 8], bpm: 168 }, [
      qd(), q(),
      eighth(), eighth(), eighth(), q(),
      tsChange(7, 8),
      qd(), q(), q(),
      eighth(), eighth(), qd(), q(),
      tsChange(3, 4),
      q(), q(), q(),
      eighth(), eighth(), eighth(), eighth(), q(),
      tsChange(6, 8),
      qd(), eighth(), eighth(), eighth(),
      eighth(), eighth(), eighth(), eighth(), eighth(), eighth(),
      tsChange(4, 4),
      q(), q(), eighth(), eighth(), q(),
      w(),
    ]),
  },
  {
    id: 'level-10-5',
    level: 10,
    indexInLevel: 5,
    name: 'Level 10 — 5',
    description: '全要素の総決算',
    bpm: 168,
    themeColor: COLOR[10],
    score: buildScore({ ts: [4, 4], bpm: 168 }, [
      eighthDotted(), sixteenth(), eighth(), eighth(), q(), q(),
      quarterTriplet(), quarterTriplet(), quarterTriplet(), tie(eighth(), q()), eighth(), q(),
      tsChange(7, 8),
      qd(), q(), q(),
      eighth(), eighth(), eighth(), qd(), q(),
      tsChange(4, 4),
      tempoChange(140),
      fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), q(), h(),
      sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), q(),
      tempoChange(168),
      h(), tie(q(), h()), q(),
      w(),
    ]),
  },
  {
    id: 'level-10-exam',
    level: 10,
    indexInLevel: 6,
    isExam: true,
    name: 'Level 10 — Exam',
    description: '卒業試験 — Rhygym の最終形',
    bpm: 168,
    themeColor: COLOR[10],
    // Level 10 final: there's no Level 11 to preview, so this stage
    // pushes every Level-10 element to its limit — meter changes per
    // measure, tempo ramps, cross-rhythms, ties across barlines, and
    // every tuplet family in rotation.
    score: buildScore({ ts: [4, 4], bpm: 168 }, [
      // 1. statement in 4/4
      eighthDotted(), sixteenth(), eighth(), eighth(), q(), q(),
      quarterTriplet(), quarterTriplet(), quarterTriplet(), h(),
      // 2. into 5/8
      tsChange(5, 8),
      qd(), q(),
      eighth(), eighth(), eighth(), q(),
      // 3. into 7/8 with a tempo dip
      tsChange(7, 8),
      tempoChange(132),
      qd(), q(), q(),
      eighth(), eighth(), qd(), q(),
      // 4. tuplet workout in 4/4, tempo restored
      tsChange(4, 4),
      tempoChange(168),
      fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), fiveTuplet(), ...septuplet(), h(),
      sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), sixTuplet(), eighthTriplet(), eighthTriplet(), eighthTriplet(), q(),
      // 5. cross-rhythm + tie + accel into the close
      quarterTriplet(), quarterTriplet(), quarterTriplet(), tie(eighth(), q()), eighth(), q(),
      tempoChange(184),
      sixteenth(), sixteenth(), sixteenth(), sixteenth(), eighth(), eighth(), q(), q(),
      // 6. final cadence — sustained
      tie(h(), h()), h(), q(), qr(),
    ]),
  },
];

function ensureDir(filepath: string): void {
  mkdirSync(dirname(filepath), { recursive: true });
}

function writeStage(stage: StageDef): void {
  const midi = scoreToMidi(stage.score);
  const midiPath = join(OUT_DIR, stage.id, 'score.mid');
  ensureDir(midiPath);
  writeFileSync(midiPath, Buffer.from(midi.toArray()));

  const { score: _score, ...meta } = stage;
  const jsonPath = join(OUT_DIR, stage.id, 'stage.json');
  writeFileSync(jsonPath, JSON.stringify(meta, null, 2));
}

function writeManifest(stages: readonly StageDef[]): void {
  const manifest = {
    version: 1,
    stages: stages.map((s) => s.id),
  };
  const manifestPath = join(OUT_DIR, 'manifest.json');
  ensureDir(manifestPath);
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
}

function main(): void {
  for (const stage of STAGE_DEFS) {
    writeStage(stage);
    console.log(`  ✓ ${stage.id}`);
  }
  writeManifest(STAGE_DEFS);
  console.log(`Generated ${STAGE_DEFS.length} stage(s) in ${OUT_DIR}/`);
}

main();
